# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024  
  end

  config.vm.define "dashboard" do |dashboard|
      dashboard.vm.box = "hashicorp/precise64"
      dashboard.vm.network "forwarded_port", guest: 8080, host: 8008,auto_correct: true
      dashboard.vm.network "forwarded_port", guest: 5005, host: 5005,auto_correct: true
  
      #refer to http://berkshelf.com/
      dashboard.berkshelf.enabled = true
      dashboard.vm.synced_folder "../DashBoard","/home/vagrant/DashBoard"
      dashboard.vm.synced_folder "../DashBoard-Client","/home/vagrant/DashBoard-Client"

      dashboard.vm.provision "chef_solo" do |chef|
        chef.add_recipe "apt"    
        chef.add_recipe "git"
        chef.add_recipe "vim"    
        chef.add_recipe "mongodb::10gen_repo"
        chef.add_recipe "mongodb"
        chef.add_recipe "grails"    

      end
  end
  
  

  

  
end
